# -*- coding: utf-8 -*-
"""reading_text_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv_-e7HuiB7KUQiUOxZijI0aSwTwk7-B
"""

import os

path = '/content/drive/MyDrive/Deep Learning - Projetos/NLP-DSA/text.txt'

with open(path, "r") as file: 
  text = file.read()

text